// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8t6sZ9DYHaduysIFqG_EffFBd56ENI0U',
    appId: '1:1057108133377:web:e445f6c3084e470964a200',
    messagingSenderId: '1057108133377',
    projectId: 'login-register-app-ui',
    authDomain: 'login-register-app-ui.firebaseapp.com',
    storageBucket: 'login-register-app-ui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC50CK2LZwVM0JDS06jl_1SG3FEUeNUR8U',
    appId: '1:1057108133377:android:9283147106b5e2ad64a200',
    messagingSenderId: '1057108133377',
    projectId: 'login-register-app-ui',
    storageBucket: 'login-register-app-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwMMfULGvI_a9qB1C-EWRFR3n9xvZxJLo',
    appId: '1:1057108133377:ios:1fba52c053cd00e864a200',
    messagingSenderId: '1057108133377',
    projectId: 'login-register-app-ui',
    storageBucket: 'login-register-app-ui.appspot.com',
    iosClientId: '1057108133377-fir47q2d98jc9v37tjsl3fvin79poh57.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegisterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwMMfULGvI_a9qB1C-EWRFR3n9xvZxJLo',
    appId: '1:1057108133377:ios:1fba52c053cd00e864a200',
    messagingSenderId: '1057108133377',
    projectId: 'login-register-app-ui',
    storageBucket: 'login-register-app-ui.appspot.com',
    iosClientId: '1057108133377-fir47q2d98jc9v37tjsl3fvin79poh57.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginRegisterApp',
  );
}
